name: sync_publish
description: Sync related packages versions.
version: 0.2.0
repository: https://github.com/nogipx/feature

executables:
  sync_publish: main

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  args: ^2.3.1
  path: ^1.8.0
  process_run: ^0.12.3+2
  collection: ^1.16.0
  yaml: ^3.1.1
  file: ^6.1.4
  glob: ^2.1.1
  pool: ^1.5.1
  pub_semver: ^2.1.3
  pub_updater: ^0.2.3
  pubspec: ^2.3.0
  dotenv: ^4.0.1
  yaml_edit: ^2.0.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
